---
- name: User Add Module
  hosts: all
  become: true
  vars:
    myuser: "pravin"
    password: "{{ 'Welcome@123' | password_hash('sha512') }}"
    mygroups:
      - wheel
      - remote

  tasks:
    - name: adding secondary group(s)
      ansible.builtin.user:
        name: "{{ myuser }}"
        groups: "{{ mygroups }}"
        append: true

    - name: Removing the expiry time of the user pravin
      ansible.builtin.user:
        name: pravin
        expires: -1

    - name: sudo without password for pravin
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: '^{{ myuser }}'
        line: '{{ myuser }} ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

